<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.sunnysuperman</groupId>
		<artifactId>ss-mountain</artifactId>
		<version>2.6.1</version>
	</parent>
	<artifactId>ss-mountain-test</artifactId>
	<name>${project.artifactId}</name>
	<packaging>jar</packaging>

	<dependencies>
		<!-- 基础框架 -->
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-core</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-web</artifactId>
		</dependency>
		<dependency>
			<groupId>jakarta.servlet</groupId>
			<artifactId>jakarta.servlet-api</artifactId>
		</dependency>
		<dependency>
			<groupId>com.sunnysuperman</groupId>
			<artifactId>ss-mountain-lang</artifactId>
		</dependency>
		<dependency>
			<groupId>com.sunnysuperman</groupId>
			<artifactId>ss-mountain-httpclient</artifactId>
		</dependency>
	</dependencies>

</project>