<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.6.15</version>
	</parent>
	<groupId>com.sunnysuperman</groupId>
	<artifactId>ss-mountain</artifactId>
	<packaging>pom</packaging>
	<version>2.7.1</version>

	<properties>
		<!-- 注意此版本号要跟着 project.version 修改 -->
		<ss-mountain.version>2.7.1</ss-mountain.version>

		<java.version>11</java.version>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>

		<spring-boot.version>2.6.15</spring-boot.version>
		<spring-cloud.version>2021.0.3</spring-cloud.version>
		<spring-cloud-alibaba.version>2021.1</spring-cloud-alibaba.version>

		<ss-validation-api.version>1.0</ss-validation-api.version>
		<reflections.version>0.10.2</reflections.version>
		<swagger-annotations.version>1.5.20</swagger-annotations.version>
		<springfox.version>3.0.0</springfox.version>
		<redisson.version>3.17.6</redisson.version>
		<xxl-job.version>2.4.0</xxl-job.version>
		<xlsx-streamer.version>2.2.0</xlsx-streamer.version>
		<aliyun-ons-client.version>1.8.8.8.Final</aliyun-ons-client.version>
		<aliyun-rocketmq-client.version>5.0.6</aliyun-rocketmq-client.version>
	</properties>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-dependencies</artifactId>
				<version>${spring-boot.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>${spring-cloud.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			<dependency>
				<groupId>com.alibaba.cloud</groupId>
				<artifactId>spring-cloud-alibaba-dependencies</artifactId>
				<version>${spring-cloud-alibaba.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>

			<dependency>
				<groupId>com.sunnysuperman</groupId>
				<artifactId>ss-validation-api</artifactId>
				<version>${ss-validation-api.version}</version>
			</dependency>
			<dependency>
				<groupId>com.sunnysuperman</groupId>
				<artifactId>ss-mountain-lang</artifactId>
				<version>${ss-mountain.version}</version>
			</dependency>
			<dependency>
				<groupId>com.sunnysuperman</groupId>
				<artifactId>ss-mountain-base</artifactId>
				<version>${ss-mountain.version}</version>
			</dependency>
			<dependency>
				<groupId>com.sunnysuperman</groupId>
				<artifactId>ss-mountain-test</artifactId>
				<version>${ss-mountain.version}</version>
			</dependency>
			<dependency>
				<groupId>com.sunnysuperman</groupId>
				<artifactId>ss-mountain-validation</artifactId>
				<version>${ss-mountain.version}</version>
			</dependency>
			<dependency>
				<groupId>com.sunnysuperman</groupId>
				<artifactId>ss-mountain-httpclient</artifactId>
				<version>${ss-mountain.version}</version>
			</dependency>
			<dependency>
				<groupId>com.sunnysuperman</groupId>
				<artifactId>ss-mountain-task</artifactId>
				<version>${ss-mountain.version}</version>
			</dependency>
			<dependency>
				<groupId>com.sunnysuperman</groupId>
				<artifactId>ss-mountain-web</artifactId>
				<version>${ss-mountain.version}</version>
			</dependency>
			<dependency>
				<groupId>com.sunnysuperman</groupId>
				<artifactId>ss-mountain-swagger2</artifactId>
				<version>${ss-mountain.version}</version>
			</dependency>
			<dependency>
				<groupId>com.sunnysuperman</groupId>
				<artifactId>ss-mountain-repository</artifactId>
				<version>${ss-mountain.version}</version>
			</dependency>
			<dependency>
				<groupId>com.sunnysuperman</groupId>
				<artifactId>ss-mountain-db</artifactId>
				<version>${ss-mountain.version}</version>
			</dependency>
			<dependency>
				<groupId>com.sunnysuperman</groupId>
				<artifactId>ss-mountain-transaction</artifactId>
				<version>${ss-mountain.version}</version>
			</dependency>
			<dependency>
				<groupId>com.sunnysuperman</groupId>
				<artifactId>ss-mountain-lock</artifactId>
				<version>${ss-mountain.version}</version>
			</dependency>
			<dependency>
				<groupId>com.sunnysuperman</groupId>
				<artifactId>ss-mountain-lock-redis</artifactId>
				<version>${ss-mountain.version}</version>
			</dependency>
			<dependency>
				<groupId>com.sunnysuperman</groupId>
				<artifactId>ss-mountain-cache</artifactId>
				<version>${ss-mountain.version}</version>
			</dependency>
			<dependency>
				<groupId>com.sunnysuperman</groupId>
				<artifactId>ss-mountain-cache-redis</artifactId>
				<version>${ss-mountain.version}</version>
			</dependency>
			<dependency>
				<groupId>com.sunnysuperman</groupId>
				<artifactId>ss-mountain-localcache</artifactId>
				<version>${ss-mountain.version}</version>
			</dependency>
			<dependency>
				<groupId>com.sunnysuperman</groupId>
				<artifactId>ss-mountain-mq</artifactId>
				<version>${ss-mountain.version}</version>
			</dependency>
			<dependency>
				<groupId>com.sunnysuperman</groupId>
				<artifactId>ss-mountain-mq-rocketmq4</artifactId>
				<version>${ss-mountain.version}</version>
			</dependency>
			<dependency>
				<groupId>com.sunnysuperman</groupId>
				<artifactId>ss-mountain-mq-rocketmq5</artifactId>
				<version>${ss-mountain.version}</version>
			</dependency>
			<dependency>
				<groupId>com.sunnysuperman</groupId>
				<artifactId>ss-mountain-job</artifactId>
				<version>${ss-mountain.version}</version>
			</dependency>
			<dependency>
				<groupId>com.sunnysuperman</groupId>
				<artifactId>ss-mountain-job-xxl</artifactId>
				<version>${ss-mountain.version}</version>
			</dependency>
			<dependency>
				<groupId>com.sunnysuperman</groupId>
				<artifactId>ss-mountain-evt</artifactId>
				<version>${ss-mountain.version}</version>
			</dependency>
			<dependency>
				<groupId>com.sunnysuperman</groupId>
				<artifactId>ss-mountain-localevent</artifactId>
				<version>${ss-mountain.version}</version>
			</dependency>
			<dependency>
				<groupId>com.sunnysuperman</groupId>
				<artifactId>ss-mountain-search</artifactId>
				<version>${ss-mountain.version}</version>
			</dependency>
			<dependency>
				<groupId>com.sunnysuperman</groupId>
				<artifactId>ss-mountain-file</artifactId>
				<version>${ss-mountain.version}</version>
			</dependency>
			<dependency>
				<groupId>com.sunnysuperman</groupId>
				<artifactId>ss-mountain-export</artifactId>
				<version>${ss-mountain.version}</version>
			</dependency>
			<dependency>
				<groupId>com.sunnysuperman</groupId>
				<artifactId>ss-mountain-randomid</artifactId>
				<version>${ss-mountain.version}</version>
			</dependency>
			<dependency>
				<groupId>com.sunnysuperman</groupId>
				<artifactId>ss-mountain-excel</artifactId>
				<version>${ss-mountain.version}</version>
			</dependency>

			<!-- others -->
			<dependency>
				<groupId>org.reflections</groupId>
				<artifactId>reflections</artifactId>
				<version>${reflections.version}</version>
			</dependency>
			<dependency>
				<groupId>io.swagger</groupId>
				<artifactId>swagger-annotations</artifactId>
				<version>${swagger-annotations.version}</version>
			</dependency>
			<dependency>
				<groupId>io.springfox</groupId>
				<artifactId>springfox-boot-starter</artifactId>
				<version>${springfox.version}</version>
			</dependency>
			<dependency>
				<groupId>org.redisson</groupId>
				<artifactId>redisson</artifactId>
				<version>${redisson.version}</version>
			</dependency>
			<dependency>
				<groupId>com.xuxueli</groupId>
				<artifactId>xxl-job-core</artifactId>
				<version>${xxl-job.version}</version>
			</dependency>
			<dependency>
				<groupId>com.monitorjbl</groupId>
				<artifactId>xlsx-streamer</artifactId>
				<version>${xlsx-streamer.version}</version>
			</dependency>

		</dependencies>
	</dependencyManagement>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<source>${java.version}</source>
					<target>${java.version}</target>
					<encoding>${project.build.sourceEncoding}</encoding>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<configuration>
					<skipTests>true</skipTests>
				</configuration>
			</plugin>
			<plugin>
				<groupId>com.diffplug.spotless</groupId>
				<artifactId>spotless-maven-plugin</artifactId>
				<version>2.23.0</version>
				<configuration>
					<formats>
						<format>
							<includes>
								<include>**/*.xml</include>
							</includes>
							<excludes>
								<exclude>assets/**/*.xml</exclude>
								<exclude>target/**/*.xml</exclude>
							</excludes>
							<eclipseWtp>
								<type>XML</type>
							</eclipseWtp>
						</format>
						<format>
							<includes>
								<include>**/*.json</include>
							</includes>
							<excludes>
								<exclude>assets/**/*.json</exclude>
								<exclude>target/**/*.json</exclude>
							</excludes>
							<eclipseWtp>
								<type>JSON</type>
							</eclipseWtp>
						</format>
					</formats>
					<java>
						<includes>
							<include>**/*.java</include>
						</includes>
						<importOrder>
							<order>java,javax,org,com,</order>
						</importOrder>
						<removeUnusedImports />
						<eclipse>
							<version>4.16.0</version>
							<file>
								${user.dir}/assets/format/eclipse-java-style-buildin.xml</file>
						</eclipse>
					</java>
				</configuration>
			</plugin>
		</plugins>
	</build>

	<modules>
		<module>ss-mountain-lang</module>
		<module>ss-mountain-base</module>
		<module>ss-mountain-test</module>
		<module>ss-mountain-validation</module>
		<module>ss-mountain-httpclient</module>
		<module>ss-mountain-task</module>
		<module>ss-mountain-web</module>
		<module>ss-mountain-swagger2</module>
		<module>ss-mountain-repository</module>
		<module>ss-mountain-db</module>
		<module>ss-mountain-transaction</module>
		<module>ss-mountain-lock</module>
		<module>ss-mountain-lock-redis</module>
		<module>ss-mountain-cache</module>
		<module>ss-mountain-cache-redis</module>
		<module>ss-mountain-localcache</module>
		<module>ss-mountain-mq</module>
		<module>ss-mountain-mq-rocketmq4</module>
		<module>ss-mountain-mq-rocketmq5</module>
		<module>ss-mountain-job</module>
		<module>ss-mountain-job-xxl</module>
		<module>ss-mountain-evt</module>
		<module>ss-mountain-localevent</module>
		<module>ss-mountain-search</module>
		<module>ss-mountain-file</module>
		<module>ss-mountain-export</module>
		<module>ss-mountain-randomid</module>
		<module>ss-mountain-excel</module>
	</modules>

</project>