package com.sunnysuperman.mountain.evt;

import java.lang.reflect.ParameterizedType;
import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

import javax.annotation.PostConstruct;

import org.springframework.jdbc.core.JdbcTemplate;

import com.sunnysuperman.mountain.lang.utils.Colls;

@SuppressWarnings({ "unchecked", "rawtypes" })
public class EvtRepositoryManager {
	private EvtClassManager evtClassMananger;
	private JdbcTemplate jdbcTemplate;
	private List<EvtRepository> repositoryList;
	private Map<Class<? extends Evt>, EvtRepository> repositoryMap;

	public EvtRepositoryManager(EvtClassManager evtClassMananger, JdbcTemplate jdbcTemplate,
			List<EvtRepository> repositoryList) {
		super();
		this.evtClassMananger = evtClassMananger;
		this.jdbcTemplate = jdbcTemplate;
		this.repositoryList = repositoryList;
	}

	@PostConstruct
	public void init() {
		// 加载自定义事件仓库
		if (Colls.isEmpty(repositoryList)) {
			repositoryMap = new HashMap<>();
		} else {
			repositoryMap = repositoryList.stream().collect(Collectors.toMap(repo -> {
				Type superClass = repo.getClass().getGenericSuperclass();
				while (!(superClass instanceof ParameterizedType)) {
					superClass = ((Class) superClass).getGenericSuperclass();
					if (superClass == Object.class) {
						break;
					}
				}
				return (Class<? extends Evt>) ((ParameterizedType) superClass).getActualTypeArguments()[0];
			}, repo -> repo));
		}
		// 自动生成事件仓库
		for (Class<?> clazz : evtClassMananger.getAll()) {
			EvtConf conf = clazz.getAnnotation(EvtConf.class);
			if (!conf.persistent()) {
				continue;
			}
			Class<? extends Evt> evtClass = (Class<? extends Evt>) clazz;
			EvtRepository repository = repositoryMap.get(evtClass);
			if (repository == null) {
				repository = new AutoGeneratedEvtRepository<>(evtClass);
			}
			repositoryMap.put(evtClass, repository);
		}
	}

	public <T extends Evt> EvtRepository<T> findRepository(Class<T> evtClass) throws EvtException {
		return repositoryMap.get(evtClass);
	}

	public <T extends Evt> EvtRepository<T> getRepository(Class<T> evtClass) throws EvtException {
		EvtRepository<T> repo = findRepository(evtClass);
		if (repo == null) {
			throw new EvtException("No evt repository found for " + evtClass);
		}
		return repo;
	}

	public EvtRepository getRepository(Evt evt) throws EvtException {
		return getRepository(evt.getClass());
	}

	private class AutoGeneratedEvtRepository<T extends Evt> extends AbstractEvtRepository<T>
			implements EvtRepository<T> {
		Class<T> evtClass;

		public AutoGeneratedEvtRepository(Class<T> evtClass) {
			super();
			this.evtClass = evtClass;
		}

		@Override
		protected Class<T> getEntityClass() {
			return evtClass;
		}

		@Override
		protected JdbcTemplate getJdbcTemplate() {
			return jdbcTemplate;
		}
	}
}
